name = "petti-api"
main = "src/index.ts"
compatibility_date = "2024-12-01"

[[d1_databases]]
binding = "DB"
database_name = "petti-shop-db"
database_id = "7a6b8d7d-2c23-478b-a9cf-47a15717ab75"
migrations_dir = "drizzle"

[vars]
ADMIN_SECRET = "petti-dev-admin-secret"

[dev]
port = 8787
